### PR TITLE
[select] translation of no value. fix #469

### LINKED ISSUE #469: [Select - new component version] no-selected-value is not translated

### PR DESCRIPTION
**Pull request by Tommass**
# Select

### Correction
Now value in select are now translated.

### fixes
fix #469

### CODE REVIEW

**Comment by pierr** [comment]
Is it the role of the select to translate values ? It is not obvious. According to me it is the role of the server to _serve_ a list which is translated. The translation of these values have no place in the client. Except for the `noValue` case

**Comment by Tommass** [comment]
@pierr yes it the right place to do it. Imagine an international app where you can switch the language ?

**Comment by pierr** [comment]
@tomass In previous applications, when the language was switched, the page was refreshed. Each request has the language in the header or in the user's session and the server know how to translate all master data. 
The problem is if you add a new element in your master data list, the client application cannot know about it you will need to deliver the app again. 
Translate the drop down content is not a problem but I think it is the wrong way to to it except of the not selected element.

**Comment by Tommass** [comment]
I am ok with your comment.

**Comment by Tommass** [comment]
@pierr i changed my correction. Please review it. Thanks.

**Pull request merged**
