### PR TITLE
openedFacetList taken into account

### PR DESCRIPTION
**Pull request by sgoretti**

### CODE REVIEW

**Comment by sgoretti** [comment]
linked to #662

**Comment by Bernardstanislas** [comment]
Awesome, thank you !

For the pull request itself, can you please try to follow this [guideline](https://github.com/KleeGroup/focus-docs/blob/master/contribute/PR_FIX_TEMPLATE.md) for the title and description.

Thank you for your help !

**Comment by Bernardstanislas** [comment]
Sorry your branch is out of date, can you please rebase it on develop ?
Thanks

**Comment by Bernardstanislas** [comment]
@sgoretti Thanks !

**Pull request merged**
