### PR TITLE
Feature react 014

### PR DESCRIPTION
**Pull request by pierr**
Migrate to React0.14 rc1 and ReactDOM see [FB](https://facebook.github.io/react/blog/2015/09/10/react-v0.14-rc1.html) blog's note about deprectation.

I had to remove the dependency to the date picker and to the react-ace component.
I thought they might be optional.

I try to add missing require react, and remove old `this.findDOMNode` methods

### CODE REVIEW

**Comment by Bernardstanislas** [comment]
Hum seems like it's not building anymore, what do you suggest ?

**Comment by Tommass** [comment]
what about the date picker ?
is it still working with React 0.14 ?

**Comment by pierr** [comment]
https://github.com/skratchdot/react-bootstrap-daterangepicker/pull/31

**Comment by pierr** [comment]
according to me we can take my fork component until it's merged into master on react bootstrap date picker

**Comment by pierr** [comment]
We need to be carefull about updating our dependencies `react-ace` and `react-bootstrap-date-picker`

**Pull request merged**
