### PR TITLE
Add warning message in search result display

### PR DESCRIPTION
**Pull request by JabX**
I just spent a lot of time trying to figure out what I did wrong there, so I'm proposing this warning to help out.

### CODE REVIEW

**Comment by pierr** [comment]
@JabX Can you rebase your branch on develop?
Thanks.

**Comment by JabX** [comment]
It's done.

**Comment by Bernardstanislas** [comment]
Sorry it's out of date once again, due to the incoming release.. Please wait until the end of the day to rebase.
Please do a real rebase, not a merge (just to keep the graph clean)

**Comment by pierr** [comment]
@JabX Sorry it's out of date once again

**Comment by pierr** [comment]
@JabX Next time can you name your branch `feature-*` or `fix-*`

**Pull request merged**
