### PR TITLE
Fix key generation

### LINKED ISSUE #1179: [ListComponent] A line can don't appear because of key generation
# Current behaviour

'focus-components/list/selection/list' : The composant generate a key with, if he exists, the data line's id or with the data' lines index. 

But if the id is equal to 0, he gonna take the index. So, if this index is equal to an other data line's id, the second line doesn't appear .

# Expected behaviour

The component should take the index in all cases.

## Versions
Focus-components: 0.15.0 (but the current 0.15.4 have still the issue)

### PR DESCRIPTION
**Pull request by JohnnP**
### Description

The index is unique, so the key will be unique.

> Fixes #1179

### CODE REVIEW

**Comment by pierr** [comment]
@JohnnP I disagree with you. The index is a bad practice, you should use a function to test if the `idFIeld` exists.
The `key` props is used by React to perform diff on the virtual dom.
If two element have the same key react recycle the component, so it is not a good practice ti use `idx` as key.

**Comment by JohnnP** [comment]
The idx of an array is always unique in this array. I don't understand the problem with the react system. 
I don't see how it's possible to have two elements with the same key.

**Comment by JohnnP** [comment]
I have create a method to generated a key if the lane doesn't have one already

**Comment by pierr** [comment]
@JohnnP The problem is not two elements with the same key. It is that if you sort, your first element can change an react will try to recycle your element.

**Comment by JohnnP** [comment]
Yes i have understood after. But i think the new version fix this problem

**Comment by TomGallon** [comment]
as Pierr tolds you: please use the `idFIeld` props.

**Pull request closed without merging**
