### PR TITLE
Add possibility to set ErrorCenter property as `null` to disable it.

### PR DESCRIPTION
**Pull request by JRLK**
### Description

Set ErrorCenter property to `null` to disable ErrorCenter component.

### Example

```jsx
const ErrorCenter = () => (null);

render(Layout, 'div#spabody', {
    props: {MenuLeft: MenuLeft, ErrorCenter: ErrorCenter}
});
```

### CODE REVIEW

**Comment by pierr** [comment]
@JRLK i think It would be better if you add a props for the error center and replace it by null or empty function when you don't need it.

**Comment by pierr** [comment]
It 's already the case see https://github.com/JRLK/focus-components/blob/patch-1/src/components/layout/index.js#L28 you just have to provide a component which is error center when you need it and null otherwise.

**Comment by JRLK** [comment]
@pierr We call the Layout in `layout-initialize.js` which have this content :
````javascript
let render = Focus.application.render;
let Layout = FocusComponents.components.Layout;
let {dispatcher} = Focus;
let MenuLeft = require('../views/menu');
let Header = require('../views/menu/header-right');

dispatcher.handleViewAction({
    data: {
        barContentRightComponent: {component: Header}
    },
    type: 'update'
});

render(Layout, 'div#spabody', {
    props: {MenuLeft: MenuLeft}
});
```

When I try to add a null or empty function like this :
````javascript
let ErrorCenter = () => null;
render(Layout, 'div#spabody', {
    props: {MenuLeft: MenuLeft, ErrorCenter: ErrorCenter}
});
```

I have the following error : 
```
Uncaught (in promise) TypeError: inst.render is not a function
    at ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (http://localhost:90/CelerisFrontEnd/javascripts/vendor.js:6058:34)
    at ReactCompositeComponentMixin._renderValidatedComponent (http://localhost:90/CelerisFrontEnd/javascripts/vendor.js:6078:32)
    at wrapper [as _renderValidatedComponent] (http://localhost:90/CelerisFrontEnd/javascripts/vendor.js:12466:21)
    at ReactCompositeComponentMixin.mountComponent (http://localhost:90/CelerisFrontEnd/javascripts/vendor.js:5691:30)
    at wrapper [as mountComponent] (http://localhost:90/CelerisFrontEnd/javascripts/vendor.js:12466:21)
    at Object.ReactReconciler.mountComponent (http://localhost:90/CelerisFrontEnd/javascripts/vendor.js:13091:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (http://localhost:90/CelerisFrontEnd/javascripts/vendor.js:11805:44)
    at ReactDOMComponent.Mixin._createContentMarkup (http://localhost:90/CelerisFrontEnd/javascripts/vendor.js:6932:32)
    at ReactDOMComponent.Mixin.mountComponent (http://localhost:90/CelerisFrontEnd/javascripts/vendor.js:6820:29)
    at Object.ReactReconciler.mountComponent (http://localhost:90/CelerisFrontEnd/javascripts/vendor.js:13091:35)
```

Can you tell me what's wrong in my code please?
Thanks

**Comment by pierr** [comment]
@JRLK Can you update the description ?

**Comment by Bernardstanislas** [comment]
@JRLK can you try with `const ErrorCenter = () => ()` ?

**Comment by JRLK** [comment]
@Bernardstanislas 
```jsx
const ErrorCenter = () => {} ; // Doesn't work : Uncaught (in promise) TypeError: inst.render is not a function)
const ErrorCenter = () => ();  // Doesn't work :  Unexpected token
const ErrorCenter = () => (null); // Works.
```

**Comment by pierr** [comment]
@JRLK @Bernardstanislas awkward

**Comment by Bernardstanislas** [comment]
@JRLK ok, good news it's fixed :)

**Pull request merged**
