### PR TITLE
Add error when it is used in fieldFor

### PR DESCRIPTION
**Pull request by JohnnP**
### Description

The component doesn't show validation error. Now, it does (I think)

### CODE REVIEW

**Comment by pierr** [comment]
@Hartorn it reminds me about the checkbox, an error has no meaning on a toggle it is true or false.

**Comment by pierr** [comment]
Cc @Ephrame @JohnnP @TomGallon

**Comment by Hartorn** [comment]
@pierr I remember this discussion, good old times...
Still, now there is a checkbox with error.
Maybe the two version should exist

**Comment by Ephrame** [comment]
@pierr : If it's required in the domain, is it normal to show an error ?

**Comment by pierr** [comment]
@JohnnP can you add a screenshot in the PR description. 
Thanks

Cc @Ephrame @Hartorn

**Comment by JohnnP** [comment]
image

**Comment by Ephrame** [comment]
@JohnnP  it's not in the Pr description like this =).

**Comment by JohnnP** [comment]
Ok. So, what is the PR description ? The first comment ?

**Comment by Ephrame** [comment]
@JohnnP Yes !

**Comment by pierr** [comment]
@JohnnP thanks

**Pull request merged**
