### PR TITLE
[layout] add flex css in top header

### LINKED ISSUE #212: [Popin & Cartridge action] cartridge action button above popin
When you scroll on a page that has cartridge actions, and then open a popin, the buttons are shown on top of the popin

image

### PR DESCRIPTION
**Pull request by Tommass**
Fix #212

### CODE REVIEW

**Comment by pierr** [comment]
Much more readable.

**Comment by pierr** [comment]
Please rebase your branch

**Comment by Tommass** [comment]
Rebase done !

**Comment by Tommass** [comment]
Fix #212

**Comment by pierr** [comment]
@Tommass sorry i merge your previous branch, rebase is once again needed.

**Comment by Tommass** [comment]
Done !
Can you please merge it ?
thx

**Comment by Bernardstanislas** [comment]
lol, can you please rebase ;)

**Pull request merged**
