### PR TITLE
remove reactid from autocomplete select

### PR DESCRIPTION
**Pull request by TomGallon**
- [x] remove `data-reactid` from the autocomplete component , use `closest` instead

### CODE REVIEW

**Comment by pierr** [comment]
@TomGallon Pliz ca

**Comment by pierr** [comment]
@TomGallon Can you provide a description

**Comment by TomGallon** [comment]
yes for sure my dear @pierr

**Comment by pierr** [comment]
@TomGallon  https://facebook.github.io/react/docs/reusable-components.html#es6-classes
```js
constructor(props) {
        super(props);
        this.autocompleteId = uniqueId('autocomplete-text-');
    };
```

**Pull request merged**
