### PR TITLE
Add dropdown in primary actions

### PR DESCRIPTION
**Pull request by JohnnP**

### CODE REVIEW

**Comment by Ephrame** [comment]
@JohnnP , the dropdown is just for the secondary action.

**Comment by JohnnP** [comment]
Because i want a second dropdown and i want to change the icon of the dropdown

**Comment by TomGallon** [comment]
@JohnnP 
can you provide a screenshot of your need. Or a wireframe ? Please.

**Comment by JohnnP** [comment]
image

**Comment by TomGallon** [comment]
@JohnnP I think your request is interesting. Some others projects will have the same need.
But you don't agree with your proposition.

Instead that providing an array of actions, we prefer to open the possibility to provide a custom component.

Can you implement that ?

**Pull request merged**
